version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/netstar
      - DATABASE_URL=postgresql+asyncpg://postgres:208251001Tito@localhost:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20825100Tito
      POSTGRES_DB: netstar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
