version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "127.0.0.1:8070:8070"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8070

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: