"""Fix foreign key case sensitivity

Revision ID: e4589e72e387
Revises: 89979501c08d
Create Date: 2024-11-27 12:24:18.907585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4589e72e387'
down_revision: Union[str, None] = '89979501c08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('products_router_id_fkey', type_='foreignkey')

    # Drop dependent tables and indices in proper order
    op.drop_index('ix_products_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_routers_ip_address', table_name='routers')
    op.drop_index('ix_routers_id', table_name='routers')
    op.drop_table('routers')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_users_email', table_name='users')
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.drop_table('users')
    # op.drop_index('ix_routers_id', table_name='routers')
    # op.drop_index('ix_routers_ip_address', table_name='routers')
    # op.drop_table('routers')
    # op.drop_index('ix_products_id', table_name='products')
    # op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('download', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('billing_period', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('router_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], name='products_router_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table('routers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='routers_pkey')
    )
    op.create_index('ix_routers_ip_address', 'routers', ['ip_address'], unique=True)
    op.create_index('ix_routers_id', 'routers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
